# Generated by Django 5.2.3 on 2025-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
